<?php

namespace Jepi\Fw\Router;

use Jepi\Fw\Config\Config;
use Jepi\Fw\IO\Input;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-08 at 23:00:53.
 */
class RouterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Router
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {

        $config = new Config();
        $config->loadFile(dirname(__FILE__) . '/../../../../JepiFw/System/config.ini');
        $this->object = new Router($config, 'Test', 'testMethod', null, new Input(array('param1' => 1, 'param2' => 2),false));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Jepi\Fw\Router\Router::getController
     */
    public function testGetController(){

        $this->assertEquals("\\App\\Controllers\\Test",$this->object->getController());
    }

    /**
     * @covers Jepi\Fw\Router\Router::getAction
     */
    public function testGetAction(){
        $this->assertEquals("testMethod", $this->object->getAction());
    }

    /**
     * @covers Jepi\Fw\Router\Router::getParameters
     */
    public function testGetParameters(){
        $parameters = $this->object->getParameters();
        $this->assertArrayHasKey("param1", $parameters);
        $this->assertArrayHasKey("param2", $parameters);
    }
}
