<?php

namespace Jepi\Fw\Security;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-08 at 23:01:04.
 */
class XssFilterTest extends \PHPUnit_Framework_TestCase {

    private $xssInjection = "<script>window.alert('hello world');</script>";
    private $xssInjectionFiltered = "window.alert(&#39;hello world&#39;);";

    /**
     * @var XssFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new XssFilter();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Jepi\Fw\Security\XssFilter::xssPreventFilter
     * @todo   Implement testXssPreventFilter().
     */
    public function testXssPreventFilter() {
        $filtered = $this->object->xssPreventFilter($this->xssInjection);
        $this->assertEquals($this->xssInjectionFiltered, $filtered);
    }

}
