<?php

namespace Jepi\Fw\Model;

use Jepi\Fw\Config\Config;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-24 at 23:37:32.
 */
class ConnectionsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Connections
     */
    public static $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public static function setUpBeforeClass() {
        $config = new Config();
        $config->loadFile(dirname(__FILE__) . '/../../../../JepiFw/App/Config/config.ini');
        self::$object = new Connections($config);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Jepi\Fw\System\Model\ConnectionsManager::openMySqlConnection
     */
    public function testOpenMySqlConnection() {
        try {
            $connection = self::$object->openMySqlConnection('default');
            $this->assertEquals("PDO", get_class($connection));
        } catch (Exception $e) {
            $this->assertTrue(false);
        }
    }

    /**
     * @depends testOpenMySqlConnection
     * @covers Jepi\Fw\System\Model\ConnectionsManager::closeConnection
     */
    public function testCloseConnection() {
        try {
            $closed = self::$object->closeConnection('default');
            $this->assertTrue($closed);
        } catch (Exception $e) {
            $this->assertTrue(false);
        }
    }

}
