<?php

namespace Jepi\Fw\Config;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-02 at 00:00:26.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Config
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Config();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Jepi\Fw\Config\Config::loadFile
     * @todo   Implement testLoadFile().
     */
    public function testLoadFile()
    {
        $this->object->loadFile(dirname(__FILE__) . '/config.ini');

        $config = $this->object->getData();
        $this->assertTrue(count($config) > 0);
        $this->assertTrue(array_key_exists('Routing',$config));
    }

    /**
     * @covers Jepi\Fw\Config\Config::loadArray
     * @todo   Implement testLoadArray().
     */
    public function testLoadArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jepi\Fw\Config\Config::getData
     * @todo   Implement testGetData().
     */
    public function testGetData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
