<?php

namespace Jepi\Fw\IO;

use Jepi\Fw\Test\FwTestBase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-12 at 14:51:17.
 */
class DataCollectionTest extends FwTestBase {

    /**
     * @var DataCollection
     */
    protected static $object;

    public static function setUpBeforeClass() {
        parent::setUpBeforeClass();
        self::$object = self::$container->get('\Jepi\Fw\IO\DataCollection');
        self::$object->setup(null);
    }

    /**
     * @covers Jepi\Fw\IO\DataCollection::get
     */
    public function testGet() {
        $this->assertEquals("Jepi\\Fw\\IO\\Input", get_class(self::$object->get()));
    }

    /**
     * @covers Jepi\Fw\IO\DataCollection::post
     */
    public function testPost() {
        $this->assertEquals("Jepi\\Fw\\IO\\Input", get_class(self::$object->post()));
    }

    /**
     * @covers Jepi\Fw\IO\DataCollection::files
     */
    public function testFiles() {
        $this->assertEquals("Jepi\\Fw\\IO\\Input", get_class(self::$object->files()));
    }

}
