<?php

namespace Jepi\Fw\IO;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-07 at 22:07:25.
 */
class InputTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Input
     */
    protected $object;
    private $xssInjection = "<script>window.alert('hello world');</script>";
    private $xssInjectionFiltered = "window.alert(&#39;hello world&#39;);";

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $_GET['prop1'] = 1;
        $_GET['prop2'] = 2;
        $_GET['prop3'] = 3;
        $_GET['xssInjection'] = $this->xssInjection;
        $_POST['attr1'] = 1;
        $_POST['attr2'] = 2;
        $_POST['attr3'] = 3;
        $_POST['xssInjection'] = $this->xssInjection;
        $this->object = new Input(false);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $_GET = array();
        $_POST = array();
    }

    /**
     * @covers Jepi\Fw\IO\Input::xssPreventFilter
     */
    public function testXssPreventFilter() {
        $filtered = $this->object->xssPreventFilter($this->xssInjection);

        $this->assertEquals($this->xssInjectionFiltered, $filtered);
    }

    /**
     * @covers Jepi\Fw\IO\Input::get
     */
    public function testGet() {
        $prop1 = $this->object->get('prop1');
        $prop2 = $this->object->get('prop2');
        $prop3 = $this->object->get('prop3');
        $xssInjection = $this->object->get('xssInjection', false);
        $xssInjectionFiltered = $this->object->get('xssInjection');
        $nonExisting = $this->object->get('testNoGetParam');

        $this->assertEquals(1,$prop1);
        $this->assertEquals(2,$prop2);
        $this->assertEquals(3,$prop3);
        $this->assertEquals($this->xssInjection,$xssInjection);
        $this->assertEquals($this->xssInjectionFiltered,$xssInjectionFiltered);
        $this->assertEquals(false, $nonExisting);
    }

    /**
     * @covers Jepi\Fw\IO\Input::post
     */
    public function testPost() {
        $prop1 = $this->object->post('attr1');
        $prop2 = $this->object->post('attr2');
        $prop3 = $this->object->post('attr3');
        $xssInjection = $this->object->post('xssInjection', false);
        $xssInjectionFiltered = $this->object->post('xssInjection');
        $nonExisting = $this->object->post('testNoGetParam');

        $this->assertEquals(1,$prop1);
        $this->assertEquals(2,$prop2);
        $this->assertEquals(3,$prop3);
        $this->assertEquals($this->xssInjection,$xssInjection);
        $this->assertEquals($this->xssInjectionFiltered,$xssInjectionFiltered);
        $this->assertEquals(false, $nonExisting);
    }

}
