<?php

namespace Jepi\Fw\IO;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-07 at 22:07:28.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Response("Hello World");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @runInSeparateProcess
     * @covers Jepi\Fw\IO\Response::send
     */
    public function testSend()
    {
        ob_start();
        $outputReturned = $this->object->send();
        $output = ob_get_clean();

        $this->assertEquals("Hello World", $output);
        $this->assertEquals("Hello World", $outputReturned);
    }
}
