<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-24 at 10:24:35.
 */
class ConfigAbstractTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ConfigAbstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ConfigAbstract;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
