<?php

namespace Jepi\Fw\FrontController;
use DI\ContainerBuilder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-27 at 08:57:35.
 */
class FrontControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var FrontController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        define('ROOT', dirname(__FILE__) . '/../../../..');

        define('FW_ROOT', ROOT . DIRECTORY_SEPARATOR . 'JepiFw');
        define('APP_ROOT', FW_ROOT . DIRECTORY_SEPARATOR . 'App');
        define('SYSTEM_ROOT', FW_ROOT . DIRECTORY_SEPARATOR . 'System');

        $containerBuilder = new ContainerBuilder();
        $containerBuilder->addDefinitions(SYSTEM_ROOT.'/di.php');
        $container = $containerBuilder->build();

        $this->object = $container->get('Jepi\Fw\FrontController\FrontController');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Jepi\Fw\FrontController\FrontController::run
     * @runInSeparateProcess
     */
    public function testRun() {
        ob_start();
        $this->object->run();
        $output = ob_get_clean();

        $this->assertEquals("Hello World", $output);
    }

}
